services:
  postgres:
    image: postgres:18.1-bookworm
    container_name: todoapp-env-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_todoapp
    ports:
      - "5432:5432"
    volumes:
      - ./out/pgdata:/var/lib/postgresql/data
    user: "1000:1000"  # Добавьте эту строку! (1000 - ваш UID)
    restart: unless-stopped
